# Generated by Django 3.2 on 2022-04-10 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_key', models.CharField(max_length=200)),
                ('players', models.ManyToManyField(to='core.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=200)),
                ('site_key', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='handsummary',
            name='game',
        ),
        migrations.AlterField(
            model_name='handsummary',
            name='player',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.player'),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AddField(
            model_name='hand',
            name='table',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.table'),
        ),
        migrations.AddField(
            model_name='handsummary',
            name='hand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.hand'),
        ),
    ]
