# Generated by Django 3.2 on 2022-04-10 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220409_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='table_name',
            new_name='name',
        ),
    ]
