# Generated by Django 3.2 on 2022-04-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_table_name_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_hero',
            field=models.BooleanField(default=False),
        ),
    ]
