# Generated by Django 3.2 on 2022-04-10 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_player_is_hero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handsummary',
            old_name='hand',
            new_name='key',
        ),
    ]
