# Generated by Django 3.2 on 2022-04-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_hand_handsummary_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handsummary',
            old_name='key',
            new_name='hand',
        ),
        migrations.RemoveField(
            model_name='handsummary',
            name='player',
        ),
    ]
