# Generated by Django 3.2 on 2022-04-17 15:18

from django.db import migrations, models

def join_hands(apps, schema_editor):
    handSummary = apps.get_model("core", "HandSummary")
    summaries = handSummary.objects.all()
    for s in summaries:
        hand = s.hand
        hand.big_blind = s.big_blind
        hand.hero_win = s.hero_win
        hand.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220410_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='big_blind',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hand',
            name='hero_win',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(join_hands)
    ]
