# Generated by Django 3.2 on 2022-04-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220417_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HandSummary',
        ),
    ]
