# Generated by Django 3.2 on 2022-04-17 20:23

import itertools
from django.db import migrations, models
import django.db.models.deletion

def populate_playing_cards(apps, schema):
    suits = ["Hearts", "Clubs", "Diamonds", "Spades"]
    ranks = ["2", "3", "4", "5", "6", "7", "8", "9", "T", "J", "Q", "K", "A"]
    assert(len(ranks) == 13)

    d = dict()
    for (i,r) in enumerate(ranks):
        d[r] = i+1 # 2 ranks 1, A ranks 13
    assert(d["2"] == 1)
    assert(d["5"] == 4)
    assert(d["A"] == 13)

    cards = apps.get_model("core", "PlayingCard")
    for (s, r) in itertools.product(suits, ranks):
        cards.objects.create(suit=s, rank=r, rank_integer=d[r])
        


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_handsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(max_length=20)),
                ('rank', models.CharField(max_length=2)),
                ('rank_integer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HoleCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(to='core.PlayingCard')),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hand')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
        ),
        migrations.RunPython(populate_playing_cards)
    ]
