# Generated by Django 3.2 on 2022-04-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
