# Generated by Django 3.2 on 2022-04-24 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_action_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
