# Generated by Django 3.2 on 2022-04-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_hand_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='starting_stack',
            field=models.IntegerField(default=0),
        ),
    ]
