# Generated by Django 3.2 on 2022-06-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_seat_starting_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='winnings',
            field=models.IntegerField(default=0),
        ),
    ]
