# Generated by Django 3.2 on 2022-06-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_seat_winnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='playingcard',
            name='suit_new',
            field=models.CharField(choices=[('S', 'Spades'), ('H', 'Hearts'), ('D', 'Diamonds'), ('C', 'Clubs')], default='S', max_length=1),
        ),
    ]
