# Generated by Django 3.2 on 2022-06-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_playingcard_suit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playingcard',
            old_name='suit_new',
            new_name='suit',
        ),
    ]
