# Generated by Django 3.2 on 2022-06-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_suit_new_playingcard_suit'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='round_new',
            field=models.CharField(choices=[('P', 'Preflop'), ('F', 'Flop'), ('T', 'Turn'), ('R', 'River')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='action',
            name='type_new',
            field=models.CharField(choices=[('B', 'Blind'), ('F', 'Fold'), ('K', 'Check'), ('C', 'Call'), ('R', 'Raise')], default='K', max_length=1),
        ),
    ]
