# Generated by Django 3.2 on 2022-06-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20220618_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='round_new',
            new_name='round',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='type_new',
            new_name='type',
        ),
    ]
