# Generated by Django 3.2 on 2022-06-18 23:46

from django.db import migrations, models

# added BLINDS as a separate round before PREFLOP
def change_blind_actions(apps, schema):
    Action = apps.get_model('core', 'Action')
    for a in Action.objects.all():
        if a.type == 'B':
            a.round = 'B'
            a.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20220618_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='round',
            field=models.CharField(choices=[('B', 'Blinds'), ('P', 'Preflop'), ('F', 'Flop'), ('T', 'Turn'), ('R', 'River')], default='P', max_length=1),
        ),
        migrations.RunPython(change_blind_actions)
    ]
