# Generated by Django 3.2 on 2022-06-21 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_action_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='metrics_fresh',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BinarySeatMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Vpip'), (2, 'Preflop Raise'), (3, 'Preflop 3Bet'), (4, 'Preflop Allin')])),
                ('eligibility', models.BooleanField(default=False)),
                ('value', models.BooleanField(default=False)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.seat')),
            ],
        ),
    ]
