# Generated by Django 3.2 on 2022-07-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_rename_time_stamp_hand_played_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='imported_time',
            field=models.DateTimeField(null=True),
        ),
    ]
